version: '3.1'

services:
  db:
    image: postgres
    container_name: schedule-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: schedule-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    volumes:
      - schedule-volume:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: schedule-adminer
    ports:
      - 8000:8080

volumes:
  schedule-volume: