# Datasource
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/schedule-db
    username: user
    password: 1234

  sql:
    init:
      mode: always
      platform: postgres

# Logging
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG

# JWT
schedule-api:
  jwt:
    expiration: ${JWT_EXPIRATION:86400000}
    secret: ${JWT_SECRET:12341234123412341234123412341234}